baseURL: "https://manbudiman.github.io/"
languageCode: "en-us"
title: "Pustaka Budiman"
theme: "hugo-xmin"
publishDir: "docs"

googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: "/"
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Files
      url: "files/"
      weight: 3
    - name: HIS
      url: "HIS/"
      weight: 4
    - name: RPS
      url: "RPS/"
      weight: 5
    - name: Bank Soal
      url: "banksoal/"
      weight: 6

params:
  description: "Kumpulan kuliah dan Catatan belajar kedokteran."
  footer: "&copy; 2025 ManBudiman | [Github](https://github.com/ManBudiman) | [Twitter](https://twitter.com/manbudiman_)" 
  custom_css: ["css/custom.css"]

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
    extensions:
      passthrough:
        enable: true
        delimiters:
          block:
            - ["\\[", "\\]"]
            - ["$$", "$$"]
          inline:
            - ["\\(", "\\)"]
            
disableKinds:
  - taxonomy       # Blocks /tags/ pages
  
taxonomies:
  tag: none        # Disables tags globally
  category: none   # Disables categories globally